### ISSUE TITLE
App description is off the bottom of panel screen in Cinnamox-Heather

### ISSUE THREAD

**Issue by vlinder2** [smurphos/cinnamox-gtk-theme#50]
The Cinnamox-Heather theme (with a bit of transparency) is fantastic, but with one exception. When the drop-down (not rise-up) menu opens in my Mint 19.1 host computer and as I move my pointer along the listed apps, app-names (e.g., Skype) and descriptions (e.g., Skype Internet Telephony) appear at the menu's bottom-right-hand corner. (For clarity, the panel is across the top, not the bottom or side of my monitor.) The description appears below the name, but unfortunately off the bottom of the menu. (I'm happy to provide a screen shot, but cannot see how to do so here.) I thought that I might try to "tweak" the code to make the window a little bit taller, but I cannot figure out a way to either import Cinnamox-Heather into Oomox or to locate the theme's configuration files. So maybe the best way to approach this is to report it as a (sort of) "bug" in the Cinnamox-Heather theme. I hope that this is not too trivial a concern to be reported as a bug.

**Comment by smurphos** [comment]
Please do provide a screenshot - you can just add the image file as an attachment. 
Have you set a text scaling factor > 1 in your Font-Settings?

Please also confirm your Cinnamon version `cinnamon --version` in a terminal.
How did you install the theme - from this repo, gnome-look or Cinnamon Spices?

**Comment by vlinder2** [comment]
Thanks for the quick response, smurphos. I have the scaling factor set at 1.5 (easier for a 70-year-old to read), and my Cinnamon version is 4.0.10. A screenshot is attached. I installed the theme via the Themes app (under Add/Remove and Search for Cinnamox) that came with my Mint (Tessa) 19.1 update from Mint (Sylvia) 18.3. Thanks again for your help!
[screenshot from vlinder2.pdf](https://github.com/smurphos/cinnamox-gtk-theme/files/3076421/screenshot.from.vlinder2.pdf)

**Comment by smurphos** [comment]
Thanks for confirming - I thought might be a text-scaling issue with the space not expanding to fit the enlarged text. I'll take a look. It should be fixable one way or another.

**Comment by vlinder2** [comment]
You nailed the problem, smurphos. With a scaling factor of 1, everything is in its place. It would be great if you could make the fix. I really, really like the theme.

**Comment by smurphos** [comment]
Hi,

Fixed here by https://github.com/smurphos/cinnamox-gtk-theme/commit/7903d60f0906bddb3d8469a9caac027beb412f54

Once https://github.com/linuxmint/cinnamon-spices-themes/pull/568 is merged you should be able to update via the Themes settings module in Cinnamon.

**Comment by vlinder2** [comment]
Many, many thanks, smurphos. Now the theme is absolutely perfect!
